
name: appName
namespace: lkhintibidze
host: helm-canary.apps.osh.devops.tbc

deployment:
  image: nexus.devops.tbc:9443/lkhintibidze/test-node-server
  tag: '1.0.0'
  replicas: 1
  containerPort: 5050

service: 
  type: NodePort
  port: 5050
