apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.name }}-route
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.host }}
  path: "/"
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ .Values.name }}-service
