
name: canary-helm
namespace: lkhintibidze
host: helm-canary.apps.osh.devops.tbc

deploymentv1:
  image: nexus.devops.tbc:9443/lkhintibidze/test-node-server
  tag: '1.0.0'
  replicas: 1
  containerPort: 5050

deploymentv2:
  image: nexus.devops.tbc:9443/lkhintibidze/test-node-server
  tag: '1.2.0'
  replicas: 1
  containerPort: 5050

service: 
  type: NodePort
  port: 5050

istio: 
  weight:
    v1: 50 
    v2: 50