apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}-virtual-svc
  namespace: {{  .Values.namespace }}
spec:
  hosts:
  - {{ .Values.host }}
  gateways:
  - {{ .Values.name }}-gateway
  http:
  - route:
    - destination:
        host: {{ .Values.name }}
   