apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{  .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{  .Values.deploymentv1.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{  .Values.deploymentv1.image }}:{{ .Values.deploymentv1.tag }}
        ports:
        - containerPort: {{  .Values.deploymentv1.containerPort }}