apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{  .Values.namespace }}
spec:
  hosts:
  - {{ .Values.host }}
  gateways:
  - {{ .Values.name }}-gateway
  http:
  - route:
    - destination:
        host: {{ .Values.name }}
        subset: v1
      weight: {{ .Values.istio.weight.v1 }}
    - destination:
        host: {{ .Values.name }}
        subset: v2
      weight: {{ .Values.istio.weight.v2 }}