apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-v2
  namespace: {{  .Values.namespace }}
  labels:
    version: v2
spec:
  replicas: {{  .Values.deploymentv2.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: v2
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{  .Values.deploymentv2.image }}:{{ .Values.deploymentv2.tag }}
        ports:
        - containerPort: {{  .Values.deploymentv2.containerPort }}